parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    kernel.listener.doctrine:
        class: 'AppBundle\Listener\DoctrineListener'
        public: false
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
